import Footer from "@src/components/footer/Footer";
import Navbar from "@src/components/navbar/Navbar";
import { Inter, Roboto, Poppins } from "next/font/google";
import { ThemeProvider } from "@src/context/ThemeContext";
import type { Metadata } from "next";
import React from "react";
import "@public/assets/css/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ObiNext App",
  description: "Generated by create next app"
};

export default ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <ThemeProvider>
        <main className="container">
          <Navbar />
          {children}
          <Footer />
        </main>
      </ThemeProvider>
    </body>
  </html>
);
